# Generated by Django 4.2.1 on 2023-05-30 20:46

from django.db import migrations
from status.models import STATUS


def create_status(apps, schema_editor):
    Status = apps.get_model('status', 'Status')
    for name in STATUS:
        Status.objects.create(name=name[0])


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_status)
    ]
