# Generated by Django 4.2.1 on 2023-05-30 20:46

from django.db import migrations


def create_status(apps, schema_editor):
    Status = apps.get_model('status', 'Status')
    status_list = ('PENDING', 'SIGNED', 'CREATED', 'CANCELLED', 'POSTPONED', 'COMPLETE')

    for name in status_list:
        Status.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_status)
    ]
